### ISSUE TITLE
issue connecting on sqlite

### ISSUE THREAD

**Issue by dbaltas** [dbaltas/commit-sniffer#16]
even though migrations run successfully I have the following error running the `repo:stats` command
My .env file 
```
DB_CONNECTION=sqlite
DB_DATABASE=database/db.sqlite
```

```
12:38:20 ➜  commit-sniffer git:(master)  touch database/db.sqlite
12:38:30 ➜  commit-sniffer git:(master)  ./artisan migrate
Migration table created successfully.
Migrating: 2017_06_06_105751_create_commit_table
Migrated:  2017_06_06_105751_create_commit_table
Migrating: 2017_06_06_123628_create_authorMap_table
Migrated:  2017_06_06_123628_create_authorMap_table
Migrating: 2017_08_15_125739_add_revert_to_commit
Migrated:  2017_08_15_125739_add_revert_to_commit
12:38:34 ➜  commit-sniffer git:(master)  ./artisan repo:stats ../some-repo


  [Illuminate\Database\QueryException]
  Database (database/db.sqlite) does not exist. (SQL: delete from sqlite_sequence where name = Commit)



  [InvalidArgumentException]
  Database (database/db.sqlite) does not exist.

12:38:41 ➜  commit-sniffer git:(master)
```

**Comment by mylk** [comment]
Hello @dbaltas!

I never noticed that issue as .env is gitignored and in there i've settings for MySQL.

I like your setup and I think we should put that in the default .env.example in order to use sqlite instead of MySQL.

Anyway, the problem is that we "chdir" to the repo's path, and that affects
the application too, so it looks for ```database/db.sqlite``` on the inspected repo.

We can use the ```-C``` option of the git command to execute git commands to other repos, instead of ```chdir```. Git itself doesn't allow executing commands to outside repositories, unless ```-C``` is used:

```
fatal: ../secret-spawn/: '../secret-spawn/' is outside repository
```

Take a look at the pull request https://github.com/dbaltas/commit-sniffer/pull/20.
